# Generated by Django 5.0.1 on 2024-01-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_activeted_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activeted',
        ),
    ]
